### ISSUE TITLE
Please provide a less colorful version

### ISSUE THREAD

**Issue by probonopd** [linuxdeepin/deepin-icon-theme#10]
Please make a version of the system icons that is more subdued (less colorful), so that applications (like Google Chrome) can be more easily recognized. If everything is very colorful, it is not so easy to distinguish between utilities that came with the system and the end-user applications.

For example, I would prefer this look

![deepinscreenshot_select-area_20171217160023](https://user-images.githubusercontent.com/2480569/34080762-6af53a3c-e343-11e7-9ddf-3fac84555d6b.png)

over the current current colorful look. (This is an extreme example. Maybe it doesn't need to be as extreme as in the picture.)

**Comment by shule1987** [comment]
Sorry，I prefer not.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
