### ISSUE TITLE
deepin-icon-theme 与 xfce4-power-manager-data 产生文件冲突

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/deepin-icon-theme#11]
您好，我是 Debian 内 deepin-icon-theme 包的维护者。

今日接获问题报告称 deepin-icon-theme 存在与 xfce4-power-manager-data 1.6.0-1 所提供文件的冲突，查看 deepin 内的 deb 包同样存在该问题。

Debian 的报告可以在 https://bugs.debian.org/888058 找到。

研究发现 deepin-icon-theme 试图在 `/usr/share/icons/hicolor/` 目录内提供软链接指向 deepin 图标，此行为应当是不可取的。根据 freedesktop.org 的 [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html)：

> In order to have a place for third party applications to install their icons there should always exist a
> theme called "hicolor" [1]. The data for the hicolor theme is available for download at: 
> http://www.freedesktop.org/software/icon-theme/. Implementations are required to look in the "hicolor" 
> theme if an icon was not found in the current theme. 

是故主题不应在 hicolor 目录内提供文件。由于第三方应用将会在 hicolor 目录内提供 fallback 图标，现在的情况随时可能产生文件冲突。

望上游能够对情况进行研究，并解决该问题。

**Comment by snyh** [comment]
因为DDE目前有很多功能需要的图标, 在其他常见主题里都是没有的, 如果不放入hicolor造成的结果就是
1. 要么强占用户使用deepin主题.
2.  要么导致切换到其他主题, 显示异常.

因此deepin-icon-theme, 通过 https://github.com/linuxdeepin/deepin-icon-theme/blob/master/hicolor.list   这个文件来自动创建部分不通用的文件.    本质上就是遵循Icon Theme Specification说明的fallback机制在处理. (至于为何不放入dde-power-balabala.deb这种包中, 是因为 icon theme 通常会在多个无关的组件中共同使用)


display-brightness-symbolic 这个目前看来是没必要放到hicolor的.  会作为bug尽快处理.

**Comment by hosiet** [comment]
OK，了解了。我的理解是如果不放入 hicolor，则这些图标无法被未特别设置使用 Deepin 主题的用户所使用。那么之后等待新版本修复 display-brightness-symbolic 的问题即可

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/30988/ 先解决文件冲突的问题。

**Comment by snyh** [comment]
Andreas Beckmann <anbe@debian.org> 说让双方自行判断到底谁应该更改的原因是

这个问题， xfce4-power-manager-data  也存在问题．　　　试想，deepin-icon-theme的这个display-brightness-symbolic图标按照xfce4的做法一样拆分到deepin-power-manager-data中去．

那么deepin-power-manager和xfce4-power-manager就直接冲突了，这样DDE和xfce4就没法共同安装了

**Comment by hosiet** [comment]
文件冲突已修复，暂时关闭该 issue。
