### ISSUE TITLE
Files with names differing only in case should not happen

### ISSUE THREAD

**Issue by romildo** [linuxdeepin/deepin-icon-theme#12]
When packaging [`deepin-icon-theme` in NixOS](https://github.com/NixOS/nixpkgs/pull/36142) we came across an issue related to different files with names that differ only in case:

```
$ ls -l $(find | sort --ignore-case | uniq --ignore-case --repeated --all-repeated)                                                                                         
-rw-rw-r-- 1 romildo romildo 8990 Nov 29 03:29 ./deepin/apps/48/texmacs.svg
-rw-rw-r-- 1 romildo romildo 7855 Nov 29 03:29 ./deepin/apps/48/TeXmacs.svg
-rw-rw-r-- 1 romildo romildo 8990 Nov 29 03:29 ./Sea/apps/scalable/texmacs.svg
-rw-rw-r-- 1 romildo romildo 7855 Nov 29 03:29 ./Sea/apps/scalable/TeXmacs.svg
```

The issue happens in operating systems like darwin, where file names are case insensitive, making it impossible to create two different files with names which differ only in case.

Could someone please fix the file names listed above?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
