### ISSUE TITLE
index.theme 的类型无效（Type=fixed）

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/deepin-icon-theme#15]
根据 [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) 中的 Table 2. Per-Directory Keys 中的内容：

Type | The type of icon sizes for the icons in this               directory. Valid types are Fixed, Scalable and               Threshold. The type decides what other keys in the               section are used. If not specified, the default is               Threshold.
-- | --

<img width="647" alt="default" src="https://user-images.githubusercontent.com/8443926/39101879-5f493dfe-46d1-11e8-893d-ac286795e546.png">

根据上图，某些 Type 未大写，故导致了下游的 bug，如 https://bugs.debian.org/896601 。

请进行修复。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.

**Comment by hosiet** [comment]
Fixed in https://github.com/linuxdeepin/deepin-icon-theme/commit/92685560330b35e593cf4d2cb66a3b32b4b9292a .
