### ISSUE TITLE
Catfish icon in deepin can scarcely be seen

### ISSUE THREAD

**Issue by sgse** [linuxdeepin/deepin-icon-theme#16]
Hello,
hope I'm right here ;-)

![deepinbildschirmfoto_bereich auswahlen_20180503163731](https://user-images.githubusercontent.com/17575778/39608740-ec641b30-4f43-11e8-8376-1de97d92304c.png)

Created one for me that everyone could use if need be.

![deepinbildschirmfoto_bereich auswahlen_20180503180140](https://user-images.githubusercontent.com/17575778/39608748-09664262-4f44-11e8-9ddd-a909cf5f2066.png)

regards
sgse

[catfish.svg.zip](https://github.com/linuxdeepin/deepin-icon-theme/files/1973043/catfish.svg.zip)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
