### ISSUE TITLE
Icon request: OpenRA

### ISSUE THREAD

**Issue by fusion809** [linuxdeepin/deepin-icon-theme#17]
Hi,

One of the finest free real-time strategy (RTS) games I know of that is available for Linux is [OpenRA](https://www.openra.net/) and I'd like to request icons for it and its bundled mods (i.e. the mods that are provided by the main [OpenRA git repo](https://github.com/OpenRA/OpenRA)) at least. The icon names would be openra-ra, openra-cnc, openra-d2k and openra-ts. openra-ts is more optional because the Tiberian Sun mod is experimental and doesn't come with the OpenRA package. Their respective official icons are:

**openra-ra**:
![openra-ra](https://user-images.githubusercontent.com/4717341/45257461-17ee1c00-b3ea-11e8-828b-12185a49c0f4.png)

**openra-cnc**:
![openra-cnc](https://user-images.githubusercontent.com/4717341/45257459-17558580-b3ea-11e8-8495-1da0cb47dcb9.png)

**openra-d2k**:
![openra-d2k](https://user-images.githubusercontent.com/4717341/45257460-17ee1c00-b3ea-11e8-9522-c65bd5ddaa6f.png)

**openra-ts**:
![openra-ts](https://user-images.githubusercontent.com/4717341/45257474-4b30ab00-b3ea-11e8-98b3-d66bfb59a376.png)

Thanks for your time,
Brenton

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
