### ISSUE TITLE
The package manager icon is barely visible on the dock

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/deepin-icon-theme#19]
https://youtu.be/fX5wpw8_Hc8

**Comment by BLumia** [comment]
Seems it's not an app which deepin delivery. Could you please check if this app is using icon from deepin theme? If do, provide the icon name will helps.

cc @shule1987

**Comment by es20490446e** [comment]
It's using:
system-software-install.svg

Found at:
[deepin/actions/24](https://github.com/linuxdeepin/deepin-icon-theme/tree/master/deepin/actions/24)
[deepin-dark/actions/24](https://github.com/linuxdeepin/deepin-icon-theme/tree/master/deepin-dark/actions/24)

**Comment by keybreak** [comment]
@BLumia 
I think should just use **deepin-appstore.svg** for this case!
Would be fast & clean solution :)

**Comment by shule1987** [comment]
I will remove them from Actions.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
