### ISSUE TITLE
[Bug] home folder's  symbolic icon is using the user-desktop symbolic icon

### ISSUE THREAD

**Issue by sergioad** [linuxdeepin/deepin-icon-theme#2]
Hello Friends of Deepin I want to report that the home folder's symbolic icon (wich is used on the Nautilus' sidebar) is the same used for the desktop, this issue should be fixed son :smile:

**Comment by snyh** [comment]
@hualet  It seems we naming home icon is still in chaos 
> ./user-home.svg
> ./deepin-user-home.svg
> ./user-home-symbolic.svg
> ./folder_home.svg
> ./folder-home.svg


@sergioad Could you post more information or post a screenshot for the problem.

**Comment by hualet** [comment]
It should've been fixed in 15.1, @sergioad have you tried to upgrade to the latest version ?

**Comment by manateelazycat** [comment]
Hey, 

This bug has fixed in Deepin 15.2, please upgrade lastest version of deepin.

BTW, we will release our own's deepin file manager in Deepin 15.3, please look forward it. ;）

Thanks again for your report!
