### ISSUE TITLE
Volume icon size in the taskbar

### ISSUE THREAD

**Issue by kyrios123** [linuxdeepin/deepin-icon-theme#20]
The volume icon seems to be larger than other icons causing the taskbar in budgie to be extended in height and then looks ugly and overlaps the top of maximized window.

![image](https://user-images.githubusercontent.com/7815316/49575873-16c67f80-f944-11e8-87a8-667ea66f0efb.png)

**Comment by shule1987** [comment]
I don't think this  is a icon issue , the size is 16X16 , your screenshot is definitely much larger.

**Comment by JonnyCodewalker** [comment]
The issue still exists with version 15.12.69. Additionally the sound icon now has a visible background square aswell: https://imgur.com/a/LPKsfNq

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
