### ISSUE TITLE
请恢复 Makefile 中的 install 目标

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/deepin-icon-theme#21]
在 82bb1de7c4 中删除了 Makefile 中的 install 目标，这对于手动安装和其他发行版的打包者来说会增加负担。即使对于 deb 系的打包，也仍然可以按照正常方式在调用 `make install` 时安装所有文件（当然仍然需要使用 `DESTDIR` 和 `PREFIX` 变量），之后在 `debian/pkgname.install` 中则没有必要手动指定安装路径，而可以使用如下的语法：

debian/deepin-icon-theme.install:

```
usr/share/icons/hicolor
usr/share/icons/deepin
usr/share/icons/deepin-dark
```

debian/sea-icon-theme.install:

```
usr/share/icons/Sea
```

与 https://github.com/linuxdeepin/deepin-icon-theme/commit/82bb1de7c47fa602ee365ae861558f0d82eb8c83#diff-b67911656ef5d18c4ae36cb6741b7965 目前的实现方式相比，这样做应当是更统一且通用的，且满足了拆出 sea-icon-theme 的需求。

cc: @deepinzhangshuang @felixonmars

**Comment by felixonmars** [comment]
+1，麻烦看一下……

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
