### ISSUE TITLE
Update firefox icon 

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/deepin-icon-theme#37]
[hicolor.zip](https://github.com/linuxdeepin/deepin-icon-theme/files/6077624/hicolor.zip)

**Comment by xmuli** [comment]
?

**Comment by vesterlay** [comment]
I apologize, I should have said that inside this archive there are extracted Firefox icons from the latest release(though, actually I don't know what's your procedure of acquiring them).

Bloom theme uses outdated Firefox icon from 2017 https://en.wikipedia.org/wiki/Firefox#Branding_and_visual_identity
Do you plan to update it?

**Comment by justforlxz** [comment]
hi, thanks for providing the firefox icon, but I see from the Papirus theme that the icon has been redrawn, and the style is relatively close.
