### ISSUE TITLE
icons in dock dissapeared

### ISSUE THREAD

**Issue by kreon28** [linuxdeepin/deepin-icon-theme#38]
Hi,

After latest KDE packages upgrade in Arch (system upgrade), all of the deepin icons are gone in the dock (except for partially working bloom classic and bloom-classic dark)

![Zrzut ekranu_dde-dock_20210315113000](https://user-images.githubusercontent.com/79510999/111140978-3f0da180-8583-11eb-81d2-6938daa760f0.png)

**Comment by leillo1975** [comment]
I have the same problem on Manjaro

**Comment by kreon28** [comment]
The problem is connected with packages: kf5 group - 5.80.0-1
Rolling down kf5 packages to 5.79 version make icons back again.

**Comment by kreon28** [comment]
I assume that Kiconthemes 5.80.0-1 was buggy.
After upgrade to 5.80.0-2, the problem has been solved.
