### ISSUE TITLE
user-trash-full-symbolic icon is missing

### ISSUE THREAD

**Issue by wangxa** [linuxdeepin/deepin-icon-theme#6]
The user-trash-full-symbolic icon is missing in the current git submission version. Please see the attached image.

![1](https://cloud.githubusercontent.com/assets/1250269/23745555/8a0761b0-04b0-11e7-9dd7-e049b7b68ae4.png)

**Comment by wangxa** [comment]
The highlighted trash bin icon for the fullness state is coming from Papirus icon theme, not Deepin's full trash bin icon. I think the easiest way to resolve this problem is just to make a symbolic link. It is not difficult, right?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
